version: '3'

services:
    nodejs-app:
        build:
          context: ./nodejsapp
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3000:3000" 
        networks:
            - interview-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - nodejs-app
        networks:
            - interview-net
    redis:
      build:
        context: ./redis
      container_name: redis
      hostname: redis
      ports:
          - "6379:6379"
      depends_on:
          - nodejs-app
      networks:
          - interview-net

networks:
  interview-net:
    external: true